<?php

require_once dirname(__FILE__).'/../../../server/lib/Configuration.php';
/**
 * Test class for Configuration.
 * Generated by PHPUnit on 2016-08-28 at 01:28:09.
 */
class ConfigurationTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Configuration
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before the test case class' first test.
     */
    public static function setUpBeforeClass()
    {
        require_once dirname(__FILE__).'/../../TestingTool.php';
        $test = new TestingTool();
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Configuration();
    }

    /**
     * @covers Configuration::__construct
     */
    public function testConstruct()
    {
        $this->assertInstanceOf('Configuration', $this->object, 'Object constructed should be a Configuration');
    }

    /**
     * @covers Configuration::get
     */
    public function testGet()
    {
        $this->assertEquals('localhost', $this->object->get('dbHost'));
    }

    /**
     * @covers Configuration::get
     */
    public function testGetUnknownKey()
    {
        $this->assertFalse($this->object->get('unknownKey'));
    }
}
